name: Setup collections-lib

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: Bogdanp/setup-racket@v0.7
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'regular'
        version: 'current'
    - run: raco pkg install --auto --no-setup collections-lib
    - run: raco setup --no-docs collections-lib
