name: Test setup-racket

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        racket-version: ['7.1', '7.2', '7.3', '7.4', '7.5', '7.6', 'current']
        variant: ['regular', 'CS']

    steps:
    - uses: actions/checkout@v2
    - uses: Bogdanp/setup-racket@v0.7
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.variant }}
        version: ${{ matrix.racket-version }}
    - run: racket --version
